packages:
  - "browser-extension"
  - "thesis-research-2026/playground"
  - "thesis-research-2026/experiments/primary-evaluation/data/pipeline"
  - "thesis-research-2026/experiments/primary-evaluation/web-app"
allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
