packages:
  - "browser-extension"
  - "playground"
  - "experiments/primary-evaluation/data/pipeline"
  - "experiments/primary-evaluation/web-app"
allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
