packages:
  - "src/browser-extension"
  - "src/playground"
  - "src/experiments/primary-evaluation/data/pipeline"
  - "src/experiments/primary-evaluation/web-app"
allowBuilds:
  esbuild: true
  sharp: true
